### ISSUE TITLE
str.split is not a function at app.post

### ISSUE THREAD

**Issue by Mlocik97** [lukeed/regexparam#12]
```
node_modules/regexparam/dist/regexparam.js:3
        var c, o, tmp, ext, keys=[], pattern='', arr = str.split('/');
                                                           ^

TypeError: str.split is not a function
    at module.exports
```

when I use

```
app.post((req, res) => {
	console.log(req.body);
	res.end();
})
```

in my server.js

**Comment by lukeed** [comment]
Hi, sorry this is unrelated and also invalid.

Unrelated because _had_ it been an issue, it'd be with your server framework (polka, I presume)

And invalid because you need to specify a route path -- only `app.use` is allowed to not have a path segment:

```js
app.post('/path', (req, res) => {
	console.log(req.body);
	res.end();
})
```

Hope that helps!
