### ISSUE TITLE
Failed to minify when used in CRA

### ISSUE THREAD

**Issue by 0xClpz** [lukeed/regexparam#2]
Hey,
this might be a longshot and not related to your repo but I tried to use your library because it matches exactly what I needed but create react app doesn't seem to be able to minify it.

Here's the error message I receive:
yarn run v1.5.1
$ react-scripts build
Creating an optimized production build...
Failed to compile.

Failed to minify the code from this file:

 	./node_modules/regexparam/dist/regexparam.es.js:1

Read more here: http://bit.ly/2tRViJ9

error An unexpected error occurred: "Command failed.
Exit code: 1
Command: sh
Arguments: -c react-scripts build
Directory: /Users/antonio/dev/sandbox/regex-param-cra
Output:
".
info If you think this is a bug, please open a bug report with the information provided in "/Users/antonio/dev/sandbox/regex-param-cra/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

I created a repo to reproduce the issue: [repo](https://github.com/0xClpz/regex-param-cra)
As you can see I simply import regexpath in the index.js

To reproduce just run: yarn && yarn build

Cheers,

**Comment by aulisius** [comment]
I think this might be useful https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#npm-run-build-fails-to-minify. 

> Note: Create React App can consume both CommonJS and ES modules. For Node.js compatibility, it is recommended that the main entry point is CommonJS. However, they can optionally provide an ES module entry point with the module field in package.json. Note that even if a library provides an ES Modules version, it should still precompile other ES6 features to ES5 if it intends to support older browsers.

**Comment by lukeed** [comment]
Thanks 😄I thought that they were running Babel on `module` entries now. We had a conversation in the past that sounded like that would be the outcome.
