### ISSUE TITLE
Ending slash is output for pattern without ending slash

### ISSUE THREAD

**Issue by TrySound** [lukeed/regexparam#5]
Hi! I decided to build own router and stuck on small mismatch with path-to-regexp behaviour.

I expect `/:page` matching `/dashboard/activities` do not include slash in the end of dashboard in exec array.
https://codesandbox.io/s/intelligent-fermat-mwv42

**Comment by lukeed** [comment]
Hey, I'll have to look at this carefully as this library is also the basis of Polka and a few other big projects. I think I can make a change without affecting anything too much (including performance), but may I ask why you're using `results[0]`? It's generally always the `[1]` result and onwards that are cared about, since those are the groups.

In that regard, there's no difference. Both are "clean" `dashboard` value

**Comment by TrySound** [comment]
`results[0]` is matched url. I use it in a few places in my project.
https://github.com/ReactTraining/react-router/blob/master/packages/react-router/modules/matchPath.js#L48

**Comment by lukeed** [comment]
Right, fair enough :) I will investigate and update here later tonight or tomorrow. I already have it working/solved locally, but I have to examine the impact & ensure nothing else is adversely affected

**Comment by TrySound** [comment]
Great! Thanks!

**Comment by lukeed** [comment]
Perhaps you knew this, but ptr doesn't always trim the trailing slash: https://codesandbox.io/s/thirsty-hopper-swxme

Just wanted to highlight that clarification while I was looking into behavioral differences

**Comment by TrySound** [comment]
I did not know. Though I don't see different in your codesandbox. Did you save it?

**Comment by lukeed** [comment]
Oops, try now

**Comment by TrySound** [comment]
I see. I think this is ok. In my app there is usually only root trailing slash which is handled separately. But I'm good if it's easier for your to consider this case too.

**Comment by lukeed** [comment]
Do you need `loose` mode? Without `loose`, the trailing is always stripped.

**Comment by TrySound** [comment]
Yes, I use match only loosely. For example on page `/dashboard` I open modal with item `/dashboard/id`. And modal uses own matcher for this.

**Comment by lukeed** [comment]
Understood, just making sure. 

I still have to investigate some dependents, but I just pushed the code (and way more tests) to #6

I have to step out for a little bit, but if you can verify that that PR behaves as expected, would be appreciated. Back soon 👍

**Comment by lukeed** [comment]
Everything in the Polka & Navaid worlds still work with this change :)

**Comment by TrySound** [comment]
Thanks Luke!

**Comment by lukeed** [comment]
No problem, thanks for checking it out :) Now live btw
