### ISSUE TITLE
Regex Pattern Differs Between Versions

### ISSUE THREAD

**Issue by travistrue2008** [lukeed/regexparam#8]
It looks like the regex output changes between versions `1.2.1` and `1.3.0` when the `loose` property is set to `true`:

v.1.2.1: `/^\/users(?:$|\/)/i`
v1.3.0: `/^\/users(?=$|\/)/i`

I get consistent output when it's not set though:

v1.2.1: `/^\/users\/?$/i`
v.1.3.0: `/^\/users\/?$/i`

**Comment by lukeed** [comment]
Yes, that's intentional. It was actually a bug fix, see #5 

Closing, but if you're seeing a specific issue that this caused please let me know and can reopen. Thanks!
